Fallback!
Añadida captura de errores

diff --git a/cpacket b/cpacket
--- a/cpacket
+++ b/cpacket
@@ -14,9 +14,9 @@ function standard () { # no options
 		if [ -d $i ]
 			then
 				newName=`echo $i | tr " " _`
-				mv $i $newName
+				$(mv $i $newName) >> /dev/null || echo "Ocurrió un error al procesar $i"
 				packed=`echo $newName.cbz`
-				zip $packed $newName/*.jpg
+				$(zip $packed $newName/*.jpg) >> /dev/null || echo "Ocurrió un error al procesar $i"
 		else
 			echo "$i no es un directorio, no será procesado."
 		fi
@@ -32,9 +32,9 @@ function inputdir () { # -d
 		if [ -d $1 ]; then
 			for i in $1 ; do
 				newName=`echo $i | tr " " _`
-				mv $i $newName
+				$(mv $i $newName) >> /dev/null || echo "Ocurrió un error al procesar $i"
 				packed=`echo $newName.cbz`
-				zip $packed $newName/*.jpg
+				$(zip $packed $newName/*.jpg) >> /dev/null || echo "Ocurrió un error al procesar $i"
 			done
 		else
 			echo "El directorio introducido no existe o no es un directorio."
